[".zplug"]
    type = "archive"
    url = "https://github.com/zplug/zplug/archive/master.tar.gz"
    exact = false
    stripComponents = 1
    refreshPeriod = "168h"

[".local/share/fcitx5/rime"]
    type = "archive"
    url = "https://github.com/iDvel/rime-ice/archive/main.tar.gz"
    exact = false
    stripComponents = 1
    refreshPeriod = "168h"

